name: lab-1 ci-pipeline

on:
  push:
    paths:
      - 'lab-1/**'
  pull_request:
    paths:
      - 'lab-1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        working-directory: lab-1
        run: make check_fmt

      - name: Run tests
        working-directory: lab-1
        run: make run_tests
