name: lab-1 ci-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Go into lab-1
        run: cd lab-1

      - name: Check formatting
        run: make check_fmt

      - name: Run tests
        run: make run_tests
